### PR TITLE
Refactor Android Gimbal bridge

### PR DESCRIPTION
**Pull request by rlepinski**
This is a pretty big refactor of the Android support.

Gimbal's service already already runs as a persistent service in the background and will auto start when the phone boots, however this does not retain the listener. I assume you added a service because you needed a place to set up the listener to forward events to Urban Airship. I was able to simplify that process by extending the base urbanairship cordova plugin to broadcast when airship is ready (will be called anytime the app starts) - https://github.com/urbanairship/phonegap-ua-push/pull/145. Now, the plugin only has to worry about calling start/stop on the adapter.

I am in the process of testing it to make sure it works the way we expect.

### CODE REVIEW

**Comment by rlepinski** [comment]
I tested it out and it seems to work fine. I see the gimbal adapter starting after reboot, if the app is killed, and when the app is first ran.

**Comment by koga73** [comment]
Do the visit events fire when the app is closed?

We have four test cases for visit events firing and push notifications:
1. App is open in foreground
2. App is open in background
3. App is closed via Recents from hardware button
4. Device is restarted

From our testing we started by just trying to call setApiKey and start / stop adapter from GimbalPlugin.java, however as soon as the app was put in the background the code was suspended and none of the visit events would fire. We dug through the sample application bundled with the Gimbal SDK and implemented the service in order to capture visit events in the background. After doing so test cases 1 and 2 worked but 3 still did not. Even in the Gimbal sample application visit events don't fire once the app is closed via Recents. We were able to fix the sample app by moving Gimbal.start() into onCommandStart in the sample AppService.

In regards to permissions we were testing on Android 23 but tried dropping the targetSdk to Android 22 so we would already have location access. In this scenario test case 3 failed and only seemed to work if the user explicitly allowed permission after the service was running and setApiKey had been called.

Some food for thought

**Comment by rlepinski** [comment]
@koga73 There are 2 parts to getting visits from Gimbal. 1) You need to start Gimbal up. 2) You need to set up a listener. When you were setting up the listener only in the cordova plugin, that code would not get run when the app restarted. The plugin only initializes when the app is foregrounded. Once you moved the listener to a service you had a place that would get called when the app is restarted because the service would return start sticky when created. For boot, the boot receiver would be called and you then you called the service. The service and receiver fixed your issues because it gave you a place to restore the listener when the app was started.

Gimbal already has a service that is started sticky, and a receiver that listens for the boot intent. This will keep gimbal listening for visits, but it does not necessarily restore the listener. The Urban Airship cordova plugin bootstraps whenever the application is created using a different mechanism. I added some code to broadcast a "ready" event after UA takesOff so this plugin has a place to initialize and restore the listener without relying on additional boot receivers and sticky services. 

The "ready" event is not released yet but you can use this branch - https://github.com/urbanairship/phonegap-ua-push/tree/next to test it out.

I tested all 4 of your use cases and was successful at receiving visits in everyone of them.

Please give it a go. Make sure you are using the https://github.com/urbanairship/phonegap-ua-push/tree/next for the base ua cordova plugin. If it all works for you I will work on a release tomorrow.

**Comment by koga73** [comment]
Makes sense. I'll test today

**Comment by koga73** [comment]
Seems to work. Thanks! Merging

**Pull request merged**
